import { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Header from "~/components/header/header";
import Footer from "~/components/footer/footer";
import ScriptClient from "../../components/script/script-client"
config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "/",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" suppressContentEditableWarning={true}>
      <body className={inter.className}>
        <ScriptClient />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
